// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkspaceNotification {
  #[prost(oneof = "workspace_notification::Payload", tags = "1, 2, 3")]
  pub payload: ::core::option::Option<workspace_notification::Payload>,
}
/// Nested message and enum types in `WorkspaceNotification`.
pub mod workspace_notification {
  #[derive(Clone, PartialEq, ::prost::Oneof)]
  pub enum Payload {
    #[prost(message, tag = "1")]
    ProfileChange(super::UserProfileChange),
    #[prost(message, tag = "2")]
    PermissionChanged(super::PermissionChanged),
    #[prost(message, tag = "3")]
    SystemNotification(super::SystemNotification),
  }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserProfileChange {
  #[prost(int64, tag = "1")]
  pub uid: i64,
  #[prost(string, optional, tag = "2")]
  pub name: ::core::option::Option<::prost::alloc::string::String>,
  #[prost(string, optional, tag = "3")]
  pub email: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PermissionChanged {
  #[prost(string, tag = "1")]
  pub object_id: ::prost::alloc::string::String,
  #[prost(uint32, tag = "2")]
  pub reason: u32,
}
/// 系统通知：用于工作空间级别的通知（成员加入、权限变更、@提及等）
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemNotification {
  /// 通知唯一ID
  #[prost(string, tag = "1")]
  pub id: ::prost::alloc::string::String,
  /// 工作空间ID
  #[prost(string, tag = "2")]
  pub workspace_id: ::prost::alloc::string::String,
  /// 通知类型：workspace_member_joined, permission_changed, mention, etc.
  #[prost(string, tag = "3")]
  pub notification_type: ::prost::alloc::string::String,
  /// 通知标题
  #[prost(string, tag = "4")]
  pub title: ::prost::alloc::string::String,
  /// 通知内容
  #[prost(string, tag = "5")]
  pub message: ::prost::alloc::string::String,
  /// 额外的JSON载荷
  #[prost(string, tag = "6")]
  pub payload_json: ::prost::alloc::string::String,
  /// 创建时间戳（秒）
  #[prost(int64, tag = "7")]
  pub created_at: i64,
  /// 接收者用户ID（0表示广播）
  #[prost(int64, tag = "8")]
  pub recipient_uid: i64,
}
