### 参数两个， 第一个是 q 输入email或者手机号    第二个参数(选填) page_no  默认1
GET http://localhost:8000/api/user/search?q=1

###


{
  "data": [
    {
      "uid": 528456431662272512,
      "uuid": "9070be33-d700-4c76-b5dc-91823246e932",
      "email": "13436574850",
      "phone": null,
      "name": "13436574850",
      "metadata": {},
      "deleted_at": null,
      "updated_at": "2025-11-22T08:35:37.551502Z",
      "created_at": "2025-11-22T08:35:37.551502Z"
    },
    {
      "uid": 528461521026551808,
      "uuid": "f3bce53a-5033-4f8b-b3cc-ddbbd9ecb1ca",
      "email": "17710054796",
      "phone": null,
      "name": "17710054796",
      "metadata": {},
      "deleted_at": null,
      "updated_at": "2025-11-22T08:55:50.951590Z",
      "created_at": "2025-11-22T08:55:50.951590Z"
    }
  ],
  "code": 0,
  "message": "Operation completed successfully."
}