### 添加协作 /api/{workspace_id}/collab/{object_id}/members/{member_user_id}
POST localhost:8000/api/workspace/22be6233-f0d2-4bc3-8854-b4e1823a772f/collab/619e9e36-b8cf-40ad-b009-0754c8cf0246/members/43e02a9d-8a79-484a-a1e5-199fcbc8493a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0M2UwMmE5ZC04YTc5LTQ4NGEtYTFlNS0xOTlmY2JjODQ5M2EiLCJhdWQiOiIiLCJleHAiOjE3NjQ3NjY0NTAsImlhdCI6MTc2NDc1OTI1MCwiZW1haWwiOiJ6eTg5NzkxMTQ5NEBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoienk4OTc5MTE0OTRAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNDNlMDJhOWQtOGE3OS00ODRhLWExZTUtMTk5ZmNiYzg0OTNhIn0sInJvbGUiOiIiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJvdHAiLCJ0aW1lc3RhbXAiOjE3NjQ3NDQ4OTF9XSwic2Vzc2lvbl9pZCI6ImE1MDEzZThjLTBjYjEtNGY1YS1iZjhhLTZjODYyMjk0YTg3MCIsImlzX2Fub255bW91cyI6ZmFsc2V9.0cOFe3onfx66fQaE246D45s9BkYeSD0aJ_eNPPfrM8I
Content-Type: application/json


### 权限变更  /api/{workspace_id}/collab/{object_id}/members/{member_user_id}
PATCH localhost:8000/api/workspace/22be6233-f0d2-4bc3-8854-b4e1823a772f/collab/619e9e36-b8cf-40ad-b009-0754c8cf0246/members/43e02a9d-8a79-484a-a1e5-199fcbc8493a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0M2UwMmE5ZC04YTc5LTQ4NGEtYTFlNS0xOTlmY2JjODQ5M2EiLCJhdWQiOiIiLCJleHAiOjE3NjQ3NjY0NTAsImlhdCI6MTc2NDc1OTI1MCwiZW1haWwiOiJ6eTg5NzkxMTQ5NEBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoienk4OTc5MTE0OTRAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNDNlMDJhOWQtOGE3OS00ODRhLWExZTUtMTk5ZmNiYzg0OTNhIn0sInJvbGUiOiIiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJvdHAiLCJ0aW1lc3RhbXAiOjE3NjQ3NDQ4OTF9XSwic2Vzc2lvbl9pZCI6ImE1MDEzZThjLTBjYjEtNGY1YS1iZjhhLTZjODYyMjk0YTg3MCIsImlzX2Fub255bW91cyI6ZmFsc2V9.0cOFe3onfx66fQaE246D45s9BkYeSD0aJ_eNPPfrM8I
Content-Type: application/json

{
  "permission_id": 1
}