### 我邀请的
GET localhost:8000/api/collab/me/sent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0M2UwMmE5ZC04YTc5LTQ4NGEtYTFlNS0xOTlmY2JjODQ5M2EiLCJhdWQiOiIiLCJleHAiOjE3NjQ3NTIwOTIsImlhdCI6MTc2NDc0NDg5MiwiZW1haWwiOiJ6eTg5NzkxMTQ5NEBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoienk4OTc5MTE0OTRAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNDNlMDJhOWQtOGE3OS00ODRhLWExZTUtMTk5ZmNiYzg0OTNhIn0sInJvbGUiOiIiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJvdHAiLCJ0aW1lc3RhbXAiOjE3NjQ3NDQ4OTF9XSwic2Vzc2lvbl9pZCI6ImE1MDEzZThjLTBjYjEtNGY1YS1iZjhhLTZjODYyMjk0YTg3MCIsImlzX2Fub255bW91cyI6ZmFsc2V9.JwYJiDSMJBf5EU6ww1C77yxgQLCx38LLDNnppSdzcOo


### 邀请我的
GET localhost:8000/api/collab/me/received
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0M2UwMmE5ZC04YTc5LTQ4NGEtYTFlNS0xOTlmY2JjODQ5M2EiLCJhdWQiOiIiLCJleHAiOjE3NjQ3NTIwOTIsImlhdCI6MTc2NDc0NDg5MiwiZW1haWwiOiJ6eTg5NzkxMTQ5NEBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoienk4OTc5MTE0OTRAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNDNlMDJhOWQtOGE3OS00ODRhLWExZTUtMTk5ZmNiYzg0OTNhIn0sInJvbGUiOiIiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJvdHAiLCJ0aW1lc3RhbXAiOjE3NjQ3NDQ4OTF9XSwic2Vzc2lvbl9pZCI6ImE1MDEzZThjLTBjYjEtNGY1YS1iZjhhLTZjODYyMjk0YTg3MCIsImlzX2Fub255bW91cyI6ZmFsc2V9.JwYJiDSMJBf5EU6ww1C77yxgQLCx38LLDNnppSdzcOo

